FROM nginx
MAINTAINER ashutoshh@linux.com
COPY samplewebapp  /usr/share/nginx/html/
# copy can also copy entire directory data 
# Note : team nginx already have supplied CMD for nginx image
# if i am not using CMD then original cmd will be recalled